// flow-typed signature: 16f0c69e5bc835af23ef2764e7f8b9f8
// flow-typed version: <<STUB>>/flat_v^2.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat' {
  declare export function flatten(Object, options: ?any): Object;
}
